Add a module not found error instead of assertion error
sindresorhus/req-from pull request #1
Opened 2017-04-25 12:19 UTC by ranyitz

If the module wasn't found, `req-from` is throwing an assertion error, this is because [resolve-from](https://github.com/sindresorhus/resolve-from) is returning `null` in case the module wasn't found.

The PR will throw a `module not found` like error, with the same code and message.

another option would be to extend `resolve-from` in order to get the original error if that's a better solution.

2017-04-27 03:26 UTC, sindresorhus commented
I would rather add a `{silent: false}` option to `resolve-from`.

2017-04-27 03:27 UTC, sindresorhus commented
I would rather change `resolve-from` to be like this module. Throw on the main export and silent when using `resolveFrom.silent()`.

2017-04-27 09:30 UTC, ranyitz commented
I agree,

The changes are on this PR - https://github.com/sindresorhus/resolve-from/pull/4

2017-04-28 08:00 UTC, sindresorhus commented
resolve-from@3 is out. Can you update this PR?

2017-04-28 08:30 UTC, sindresorhus commented
You also need to fix the merge conflict.

2017-04-28 08:38 UTC, ranyitz commented
Updated, thanks for the quick response !

2017-04-28 08:41 UTC, SamVerschueren requested changes
Can you also rename `fn` to `m` in the tests?

2017-04-28 08:41 UTC, SamVerschueren commented on test.js
> +test('reqFrom', t => {
`reqFrom()`

2017-04-28 08:41 UTC, SamVerschueren commented on test.js
> +test('reqFrom,silent', t => {
`reqFrom.silent()`

2017-04-28 08:49 UTC, SamVerschueren approved these changes

2017-04-28 09:01 UTC, merged

2017-04-28 09:01 UTC, sindresorhus commented
Thank you @ranyitz :)

2017-04-28 09:25 UTC, ranyitz commented
No problem, Thank you @sindresorhus @SamVerschueren :)