Use native `createRequireFromPath` function when available
sindresorhus/req-from pull request #6
Opened 2018-10-17 10:32 UTC by gillesdemey

fixes #5

2018-10-17 11:01 UTC, gillesdemey commented
Travis fails on Node 4 because `xo` is incompatible, should we just remove Node 4 from the version matrix?

2019-01-19 19:13 UTC, kevva requested changes

2019-01-19 19:13 UTC, kevva commented on index.js
> +const requireFromPath = hasNativeFunction ?
This is a bit more readable:

```js
const requireFromPath = (fromDir, moduleId) => {
	if (!hasNativeFunction) {
		return require(resolveFrom(fromDir, moduleId));
	}

	return Module.createRequireFromPath(path.resolve(fromDir, 'index.js'))(moduleId);
};
```

2019-01-19 19:13 UTC, kevva commented on index.js
> +
```suggestion

```

2019-01-20 15:29 UTC, gillesdemey commented
Done, PTAL :)

2019-01-20 15:47 UTC, kevva approved these changes

2019-05-29 18:43 UTC, sindresorhus commented
`createRequireFromPath` is deprecated in favor of `createRequire`.

2019-07-07 14:30 UTC, closed without merging